### ISSUE TITLE
Docs release gh-action doesn't use the cached python environment

### ISSUE THREAD

**Issue by rickstaa** [rickstaa/stable-learning-control#119]
Currently, the docs release gh-action is not using caching (see [this run](https://github.com/rickstaa/bayesian-learning-control/runs/2195695273?check_suite_focus=true)). Caching in the Mac and Linux Github actions seems to be working fine (see [this run](https://github.com/rickstaa/bayesian-learning-control/actions/runs/687447229)). I will leave this for now but open a question on the [cache/issues](https://github.com/actions/cache/issues) page of [github community forum](https://github.community/) when the BLC package is public. Only difference I could find is that the Os related actions use a python matrix where the other actions use a hardcoded python value:

```yml
matrix:
  python-version: [3.6, 3.7, 3.8] # Supported python versions
...
with:
   python-version: ${{ matrix.python-version }}
```

vs 

```yml
with:
    python-version: 3.7
```
